
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/localhost_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=demo
spring.datasource.password=123456

# MyBatis-Plus ??
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# SQL 日志更明显（可按需调低）
logging.level.com.baomidou.mybatisplus=DEBUG
logging.level.org.mybatis=DEBUG
